// Mocks generated by Mockito 5.4.6 from annotations
// in tvseries/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i8;
import 'dart:typed_data' as _i9;

import 'package:core/core.dart' as _i6;
import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:tvseries/tvseries.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvSeriesDetailModel_1 extends _i1.SmartFake
    implements _i3.TvSeriesDetailModel {
  _FakeTvSeriesDetailModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_2 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_3 extends _i1.SmartFake
    implements _i4.StreamedResponse {
  _FakeStreamedResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TVSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesRepository extends _i1.Mock
    implements _i3.TVSeriesRepository {
  MockTVSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i3.TvSeriesEntity>>>
  getNowPlayingTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingTVSeries, []),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, List<_i3.TvSeriesEntity>>
                >.value(
                  _FakeEither_0<_i6.Failure, List<_i3.TvSeriesEntity>>(
                    this,
                    Invocation.method(#getNowPlayingTVSeries, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i3.TvSeriesEntity>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i3.TvSeriesEntity>>>
  getPopularTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTVSeries, []),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, List<_i3.TvSeriesEntity>>
                >.value(
                  _FakeEither_0<_i6.Failure, List<_i3.TvSeriesEntity>>(
                    this,
                    Invocation.method(#getPopularTVSeries, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i3.TvSeriesEntity>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i3.TvSeriesEntity>>>
  getTopRatedTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTVSeries, []),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, List<_i3.TvSeriesEntity>>
                >.value(
                  _FakeEither_0<_i6.Failure, List<_i3.TvSeriesEntity>>(
                    this,
                    Invocation.method(#getTopRatedTVSeries, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i3.TvSeriesEntity>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i3.TvSeriesDetail>> getTVSeriesDetail(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTVSeriesDetail, [id]),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i3.TvSeriesDetail>>.value(
                  _FakeEither_0<_i6.Failure, _i3.TvSeriesDetail>(
                    this,
                    Invocation.method(#getTVSeriesDetail, [id]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i3.TvSeriesDetail>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i3.TvSeriesEntity>>>
  getTVSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTVSeriesRecommendations, [id]),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, List<_i3.TvSeriesEntity>>
                >.value(
                  _FakeEither_0<_i6.Failure, List<_i3.TvSeriesEntity>>(
                    this,
                    Invocation.method(#getTVSeriesRecommendations, [id]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i3.TvSeriesEntity>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i3.TvSeriesEntity>>> searchTVSeries(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchTVSeries, [query]),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, List<_i3.TvSeriesEntity>>
                >.value(
                  _FakeEither_0<_i6.Failure, List<_i3.TvSeriesEntity>>(
                    this,
                    Invocation.method(#searchTVSeries, [query]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i3.TvSeriesEntity>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> saveWatchlist(
    _i3.TvSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveWatchlist, [tvSeries]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
              _FakeEither_0<_i6.Failure, String>(
                this,
                Invocation.method(#saveWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, String>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> removeWatchlist(
    _i3.TvSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [tvSeries]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
              _FakeEither_0<_i6.Failure, String>(
                this,
                Invocation.method(#removeWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, String>>);

  @override
  _i5.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isAddedToWatchlist, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i3.TvSeriesEntity>>>
  getWatchlistTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTVSeries, []),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, List<_i3.TvSeriesEntity>>
                >.value(
                  _FakeEither_0<_i6.Failure, List<_i3.TvSeriesEntity>>(
                    this,
                    Invocation.method(#getWatchlistTVSeries, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i3.TvSeriesEntity>>>);
}

/// A class which mocks [TVSeriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesRemoteDataSource extends _i1.Mock
    implements _i3.TVSeriesRemoteDataSource {
  MockTVSeriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.TvSeriesModel>> getPopularTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTvSeries, []),
            returnValue: _i5.Future<List<_i3.TvSeriesModel>>.value(
              <_i3.TvSeriesModel>[],
            ),
          )
          as _i5.Future<List<_i3.TvSeriesModel>>);

  @override
  _i5.Future<List<_i3.TvSeriesModel>> getNowPlayingSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingSeries, []),
            returnValue: _i5.Future<List<_i3.TvSeriesModel>>.value(
              <_i3.TvSeriesModel>[],
            ),
          )
          as _i5.Future<List<_i3.TvSeriesModel>>);

  @override
  _i5.Future<List<_i3.TvSeriesModel>> getTopRatedSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedSeries, []),
            returnValue: _i5.Future<List<_i3.TvSeriesModel>>.value(
              <_i3.TvSeriesModel>[],
            ),
          )
          as _i5.Future<List<_i3.TvSeriesModel>>);

  @override
  _i5.Future<List<_i3.TvSeriesModel>> searchTVSeries(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTVSeries, [query]),
            returnValue: _i5.Future<List<_i3.TvSeriesModel>>.value(
              <_i3.TvSeriesModel>[],
            ),
          )
          as _i5.Future<List<_i3.TvSeriesModel>>);

  @override
  _i5.Future<_i3.TvSeriesDetailModel> getTvSeriesDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesDetail, [id]),
            returnValue: _i5.Future<_i3.TvSeriesDetailModel>.value(
              _FakeTvSeriesDetailModel_1(
                this,
                Invocation.method(#getTvSeriesDetail, [id]),
              ),
            ),
          )
          as _i5.Future<_i3.TvSeriesDetailModel>);

  @override
  _i5.Future<List<_i3.TvSeriesModel>> getTVSeriesRecommendation(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTVSeriesRecommendation, [id]),
            returnValue: _i5.Future<List<_i3.TvSeriesModel>>.value(
              <_i3.TvSeriesModel>[],
            ),
          )
          as _i5.Future<List<_i3.TvSeriesModel>>);
}

/// A class which mocks [TVSeriesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesLocalDataSource extends _i1.Mock
    implements _i3.TVSeriesLocalDataSource {
  MockTVSeriesLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> insertWatchlist(_i3.TVSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [tvSeries]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#insertWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> removeWatchlist(_i3.TVSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [tvSeries]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#removeWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i3.TVSeriesTable?> getTVSeriesById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTVSeriesById, [id]),
            returnValue: _i5.Future<_i3.TVSeriesTable?>.value(),
          )
          as _i5.Future<_i3.TVSeriesTable?>);

  @override
  _i5.Future<List<_i3.TVSeriesTable>> getWatchlistTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTVSeries, []),
            returnValue: _i5.Future<List<_i3.TVSeriesTable>>.value(
              <_i3.TVSeriesTable>[],
            ),
          )
          as _i5.Future<List<_i3.TVSeriesTable>>);
}

/// A class which mocks [TVSeriesDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesDao extends _i1.Mock implements _i3.TVSeriesDao {
  MockTVSeriesDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.TVSeriesTable?> getTVSeriesById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTVSeriesById, [id]),
            returnValue: _i5.Future<_i3.TVSeriesTable?>.value(),
          )
          as _i5.Future<_i3.TVSeriesTable?>);

  @override
  _i5.Future<int> insertTVSeries(_i3.TVSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#insertTVSeries, [tvSeries]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> updateTVSeries(_i3.TVSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#updateTVSeries, [tvSeries]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> deleteTVSeries(_i3.TVSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTVSeries, [tvSeries]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.TVSeriesTable>> getAllTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTVSeries, []),
            returnValue: _i5.Future<List<_i3.TVSeriesTable>>.value(
              <_i3.TVSeriesTable>[],
            ),
          )
          as _i5.Future<List<_i3.TVSeriesTable>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i4.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i4.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i8.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i8.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i8.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i8.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i9.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i5.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
          )
          as _i5.Future<_i9.Uint8List>);

  @override
  _i5.Future<_i4.StreamedResponse> send(_i4.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i5.Future<_i4.StreamedResponse>.value(
              _FakeStreamedResponse_3(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i5.Future<_i4.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}
