// Mocks generated by Mockito 5.4.6 from annotations
// in tvseries/test/presentation/bloc/tvseries_detail_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:core/core.dart' as _i5;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tvseries/tvseries.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTVSeriesRepository_0 extends _i1.SmartFake
    implements _i2.TVSeriesRepository {
  _FakeTVSeriesRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetTVSeriesDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTVSeriesDetail extends _i1.Mock implements _i2.GetTVSeriesDetail {
  MockGetTVSeriesDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TVSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVSeriesRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TVSeriesRepository);

  @override
  _i4.Future<_i3.Either<_i5.Failure, _i2.TvSeriesDetail>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i4.Future<_i3.Either<_i5.Failure, _i2.TvSeriesDetail>>.value(
                  _FakeEither_1<_i5.Failure, _i2.TvSeriesDetail>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i4.Future<_i3.Either<_i5.Failure, _i2.TvSeriesDetail>>);
}

/// A class which mocks [GetTVSeriesRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTVSeriesRecommendations extends _i1.Mock
    implements _i2.GetTVSeriesRecommendations {
  MockGetTVSeriesRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TVSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVSeriesRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TVSeriesRepository);

  @override
  _i4.Future<_i3.Either<_i5.Failure, List<_i2.TvSeriesEntity>>> execute(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i4.Future<
                  _i3.Either<_i5.Failure, List<_i2.TvSeriesEntity>>
                >.value(
                  _FakeEither_1<_i5.Failure, List<_i2.TvSeriesEntity>>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i4.Future<_i3.Either<_i5.Failure, List<_i2.TvSeriesEntity>>>);
}

/// A class which mocks [GetWatchlistTVSeriesStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistTVSeriesStatus extends _i1.Mock
    implements _i2.GetWatchlistTVSeriesStatus {
  MockGetWatchlistTVSeriesStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TVSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVSeriesRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TVSeriesRepository);

  @override
  _i4.Future<bool> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [SaveWatchlistTVSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistTVSeries extends _i1.Mock
    implements _i2.SaveWatchlistTVSeries {
  MockSaveWatchlistTVSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TVSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVSeriesRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TVSeriesRepository);

  @override
  _i4.Future<_i3.Either<_i5.Failure, String>> execute(
    _i2.TvSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [tvSeries]),
            returnValue: _i4.Future<_i3.Either<_i5.Failure, String>>.value(
              _FakeEither_1<_i5.Failure, String>(
                this,
                Invocation.method(#execute, [tvSeries]),
              ),
            ),
          )
          as _i4.Future<_i3.Either<_i5.Failure, String>>);
}

/// A class which mocks [RemoveWatchlistTVSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistTVSeries extends _i1.Mock
    implements _i2.RemoveWatchlistTVSeries {
  MockRemoveWatchlistTVSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TVSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVSeriesRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TVSeriesRepository);

  @override
  _i4.Future<_i3.Either<_i5.Failure, String>> execute(
    _i2.TvSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [tvSeries]),
            returnValue: _i4.Future<_i3.Either<_i5.Failure, String>>.value(
              _FakeEither_1<_i5.Failure, String>(
                this,
                Invocation.method(#execute, [tvSeries]),
              ),
            ),
          )
          as _i4.Future<_i3.Either<_i5.Failure, String>>);
}
