// Mocks generated by Mockito 5.4.6 from annotations
// in tvseries/test/presentation/pages/tvseries_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_bloc/flutter_bloc.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tvseries/tvseries.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetTVSeriesDetail_0 extends _i1.SmartFake
    implements _i2.GetTVSeriesDetail {
  _FakeGetTVSeriesDetail_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTVSeriesRecommendations_1 extends _i1.SmartFake
    implements _i2.GetTVSeriesRecommendations {
  _FakeGetTVSeriesRecommendations_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchlistTVSeriesStatus_2 extends _i1.SmartFake
    implements _i2.GetWatchlistTVSeriesStatus {
  _FakeGetWatchlistTVSeriesStatus_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaveWatchlistTVSeries_3 extends _i1.SmartFake
    implements _i2.SaveWatchlistTVSeries {
  _FakeSaveWatchlistTVSeries_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveWatchlistTVSeries_4 extends _i1.SmartFake
    implements _i2.RemoveWatchlistTVSeries {
  _FakeRemoveWatchlistTVSeries_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvseriesDetailState_5 extends _i1.SmartFake
    implements _i2.TvseriesDetailState {
  _FakeTvseriesDetailState_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TvseriesDetailCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvseriesDetailCubit extends _i1.Mock
    implements _i2.TvseriesDetailCubit {
  MockTvseriesDetailCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTVSeriesDetail get getTvSeriesDetail =>
      (super.noSuchMethod(
            Invocation.getter(#getTvSeriesDetail),
            returnValue: _FakeGetTVSeriesDetail_0(
              this,
              Invocation.getter(#getTvSeriesDetail),
            ),
          )
          as _i2.GetTVSeriesDetail);

  @override
  _i2.GetTVSeriesRecommendations get getTVSeriesRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#getTVSeriesRecommendations),
            returnValue: _FakeGetTVSeriesRecommendations_1(
              this,
              Invocation.getter(#getTVSeriesRecommendations),
            ),
          )
          as _i2.GetTVSeriesRecommendations);

  @override
  _i2.GetWatchlistTVSeriesStatus get getWatchlistStatus =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchlistStatus),
            returnValue: _FakeGetWatchlistTVSeriesStatus_2(
              this,
              Invocation.getter(#getWatchlistStatus),
            ),
          )
          as _i2.GetWatchlistTVSeriesStatus);

  @override
  _i2.SaveWatchlistTVSeries get saveWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#saveWatchlist),
            returnValue: _FakeSaveWatchlistTVSeries_3(
              this,
              Invocation.getter(#saveWatchlist),
            ),
          )
          as _i2.SaveWatchlistTVSeries);

  @override
  _i2.RemoveWatchlistTVSeries get removeWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#removeWatchlist),
            returnValue: _FakeRemoveWatchlistTVSeries_4(
              this,
              Invocation.getter(#removeWatchlist),
            ),
          )
          as _i2.RemoveWatchlistTVSeries);

  @override
  _i2.TvseriesDetailState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTvseriesDetailState_5(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.TvseriesDetailState);

  @override
  _i3.Stream<_i2.TvseriesDetailState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i3.Stream<_i2.TvseriesDetailState>.empty(),
          )
          as _i3.Stream<_i2.TvseriesDetailState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i3.Future<void> fetchTvseriesDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTvseriesDetail, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> fetchTvseriesDetailRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTvseriesDetailRecommendations, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> getTvseriesWatchlistStatus(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvseriesWatchlistStatus, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveTvseriesWatchlist(_i2.TvSeriesDetail? tvSeriesDetail) =>
      (super.noSuchMethod(
            Invocation.method(#saveTvseriesWatchlist, [tvSeriesDetail]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeTvseriesWatchlist(
    _i2.TvSeriesDetail? tvSeriesDetail,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeTvseriesWatchlist, [tvSeriesDetail]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void emit(_i2.TvseriesDetailState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i4.Change<_i2.TvseriesDetailState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
