// Mocks generated by Mockito 5.4.6 from annotations
// in tvseries/test/presentation/pages/tvseries_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:core/core.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:tvseries/tvseries.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetTVSeriesDetail_0 extends _i1.SmartFake
    implements _i2.GetTVSeriesDetail {
  _FakeGetTVSeriesDetail_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTVSeriesRecommendations_1 extends _i1.SmartFake
    implements _i2.GetTVSeriesRecommendations {
  _FakeGetTVSeriesRecommendations_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchlistTVSeriesStatus_2 extends _i1.SmartFake
    implements _i2.GetWatchlistTVSeriesStatus {
  _FakeGetWatchlistTVSeriesStatus_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaveWatchlistTVSeries_3 extends _i1.SmartFake
    implements _i2.SaveWatchlistTVSeries {
  _FakeSaveWatchlistTVSeries_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveWatchlistTVSeries_4 extends _i1.SmartFake
    implements _i2.RemoveWatchlistTVSeries {
  _FakeRemoveWatchlistTVSeries_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvSeriesDetail_5 extends _i1.SmartFake
    implements _i2.TvSeriesDetail {
  _FakeTvSeriesDetail_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TVSeriesDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesDetailNotifier extends _i1.Mock
    implements _i2.TVSeriesDetailNotifier {
  MockTVSeriesDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTVSeriesDetail get getTVSeriesDetail =>
      (super.noSuchMethod(
            Invocation.getter(#getTVSeriesDetail),
            returnValue: _FakeGetTVSeriesDetail_0(
              this,
              Invocation.getter(#getTVSeriesDetail),
            ),
          )
          as _i2.GetTVSeriesDetail);

  @override
  _i2.GetTVSeriesRecommendations get getTVSeriesRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#getTVSeriesRecommendations),
            returnValue: _FakeGetTVSeriesRecommendations_1(
              this,
              Invocation.getter(#getTVSeriesRecommendations),
            ),
          )
          as _i2.GetTVSeriesRecommendations);

  @override
  _i2.GetWatchlistTVSeriesStatus get getWatchlistTVSeriesStatus =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchlistTVSeriesStatus),
            returnValue: _FakeGetWatchlistTVSeriesStatus_2(
              this,
              Invocation.getter(#getWatchlistTVSeriesStatus),
            ),
          )
          as _i2.GetWatchlistTVSeriesStatus);

  @override
  _i2.SaveWatchlistTVSeries get saveWatchlistTVSeries =>
      (super.noSuchMethod(
            Invocation.getter(#saveWatchlistTVSeries),
            returnValue: _FakeSaveWatchlistTVSeries_3(
              this,
              Invocation.getter(#saveWatchlistTVSeries),
            ),
          )
          as _i2.SaveWatchlistTVSeries);

  @override
  _i2.RemoveWatchlistTVSeries get removeWatchlistTVSeries =>
      (super.noSuchMethod(
            Invocation.getter(#removeWatchlistTVSeries),
            returnValue: _FakeRemoveWatchlistTVSeries_4(
              this,
              Invocation.getter(#removeWatchlistTVSeries),
            ),
          )
          as _i2.RemoveWatchlistTVSeries);

  @override
  _i2.TvSeriesDetail get tvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#tvSeries),
            returnValue: _FakeTvSeriesDetail_5(
              this,
              Invocation.getter(#tvSeries),
            ),
          )
          as _i2.TvSeriesDetail);

  @override
  _i3.RequestState get tvSeriesState =>
      (super.noSuchMethod(
            Invocation.getter(#tvSeriesState),
            returnValue: _i3.RequestState.Empty,
          )
          as _i3.RequestState);

  @override
  List<_i2.TvSeriesEntity> get tvSeriesRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#tvSeriesRecommendations),
            returnValue: <_i2.TvSeriesEntity>[],
          )
          as List<_i2.TvSeriesEntity>);

  @override
  _i3.RequestState get recommendationState =>
      (super.noSuchMethod(
            Invocation.getter(#recommendationState),
            returnValue: _i3.RequestState.Empty,
          )
          as _i3.RequestState);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get isAddedToWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#isAddedToWatchlist),
            returnValue: false,
          )
          as bool);

  @override
  String get watchlistMessage =>
      (super.noSuchMethod(
            Invocation.getter(#watchlistMessage),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#watchlistMessage),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> fetchTVSeriesDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTVSeriesDetail, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addWatchlist(_i2.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#addWatchlist, [tvSeries]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeFromWatchlist(_i2.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromWatchlist, [tvSeries]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> loadWatchlistStatus(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#loadWatchlistStatus, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
